services:

  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - vault_file:/vault/file
      - ./vault/config:/vault/config:ro
      - ./shared:/shared
    command: vault server -config=/vault/config/vault.hcl

  certinfo:
    build:
      context: ./certinfo
      dockerfile: Containerfile      
    container_name: certinfo
    restart: unless-stopped
    environment:
      # cert reading
      CERT_PATH: /shared/certs/nginx.crt
      CHAIN_PATH: /shared/certs/nginx.chain.crt
      CRL_PATH: /shared/www/crl/pki-int.crl.pem
      # CAaS issuing
      DEFAULT_OUT_BASE: /shared/www/issued
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN:?set VAULT_TOKEN in your env}
      PORT: "3000"
    volumes:
      - ./shared:/shared
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      certinfo:
        condition: service_healthy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./shared/certs:/etc/nginx/certs:ro
      - ./shared/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./shared/www:/usr/share/nginx/html:ro

  ssh-container:
    build:
      context: ./ssh-container
      dockerfile: Containerfile      
    container_name: ssh-container
    restart: unless-stopped      
    ports:
      - "2222:22"
    volumes:
      - ./vault/templates:/vault/templates:ro
      - ./vault/creds/role_id:/vault/creds/role_id:ro
      - ./vault/creds/secret_id:/vault/creds/secret_id:ro
      - ./vault/vault-agent-ssh-container.hcl:/etc/vault-agent.d/vault-agent.hcl:ro
    environment:
      VAULT_ADDR: "http://vault:8200"
    depends_on:
      - vault


volumes:
  vault_file: null
